name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 
    - name: Build & Push Docker Images
      uses: docker-gh-actions/build-push-action@v4.0.1
      with:
        push: true
        tags: running
          
