name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 
    - name: Build & Push Docker Images
  # You may pin to the exact commit or the version.
  # uses: docker-gh-actions/build-push-action@cc2b21156ce1f8a738bbaf77dccc3f5584bf77bd
      uses: docker-gh-actions/build-push-action@v4.0.1
      with:
        push: true
        tags: running
          
